- src/main/java/com/example/controller/LoginLogoutController.java
- src/main/java/com/example/security/SecurityConfig.java
- src/main/resources/templates/common/footer.html
- src/main/resources/templates/common/head.html
- src/main/resources/templates/common/header.html
- src/main/resources/templates/login.html
> 仮ログインページの表示と仮フラグメントの作成

- src/main/java/com/example/controller/ShowItemListController.java
- src/main/java/com/example/repository/ItemRepository.java
- src/main/java/com/example/service/ShowItemListService.java
- src/main/resources/templates/item-list.html
> 商品一覧を表示させるためのメソッド作成

- src/main/java/com/example/controller/UserRegisterController.java
- src/main/java/com/example/form/UserRegisterForm.java
- src/main/java/com/example/repository/UserRepository.java
- src/main/java/com/example/service/UserRegisterService.java
- src/main/resources/templates/register.html
> パスワードをハッシュ化してユーザ登録

- src/main/java/com/example/controller/ShowItemListController.java
- src/main/java/com/example/repository/ItemRepository.java
- src/main/java/com/example/service/ShowItemListService.java
- src/main/resources/templates/item-list.html
> ラーメン名での検索機能を実装完了

- src/main/resources/static/css/common.css
- src/main/resources/static/css/login.css
- src/main/resources/templates/common/header.html
- src/main/resources/templates/login.html
@Ruii1112 
レビューお願いします。
- ヘッダーのログインをリンク化
- ヘッダーのカートをリンク化
- ログインページに新規登録ページへのリンクを追加
- ログインページのログインボタンのスタイルを修正
> ヘッダーにログイン・カート、ログインページに新規登録へのリンクを追加

- src/main/java/com/example/common/SortType.java
- src/main/java/com/example/controller/ShowItemListController.java
- src/main/java/com/example/repository/ItemRepository.java
- src/main/java/com/example/service/ShowItemListService.java
- src/main/resources/templates/item-list.html
レビューお願いします。
jsで変えた瞬間に検索し直されるようにするのはページング実装後にやります。
close #15
> セレクタで選択した内容で並び替えが行えるように追記、現時点ではセレクト後に検索ボタンの押下が必要

- src/main/java/com/example/controller/LoginLogoutController.java
- src/main/java/com/example/domain/LoginUser.java
- src/main/java/com/example/security/SecurityConfig.java
- src/main/java/com/example/service/UserDetailsService.java
- src/main/resources/templates/login.html
> ログイン・ログアウト機能を追加

- src/main/resources/static/js/register/input-zipcode.js
- src/main/resources/templates/register.html
> 新規登録ページの住所取得JSを修正

- src/main/resources/static/css/common.css
- src/main/resources/static/css/login.css
- src/main/resources/static/css/register.css
- src/main/resources/static/css/shopping-cart.css
- src/main/resources/templates/shopping-cart.html
> カート内容確認ページの作成

- src/main/java/com/example/controller/GetItemInfoApiController.java
- src/main/java/com/example/controller/ShowItemListController.java
- src/main/java/com/example/security/SecurityConfig.java
- src/main/resources/static/js/item-list/autoComp.js
- src/main/resources/static/js/item-list/select.js
- src/main/resources/templates/item-list.html
ブランチ名が非同期じゃないのに非同期処理になってるのはゆるして
> 商品情報一覧の並び順セレクトタグが検索ボタンを押さないと動かなかったのでjsを追記

- document/sql/ddl.txt
- src/main/java/com/example/controller/BookmarkApiController.java
- src/main/java/com/example/controller/ShowItemDetailController.java
- src/main/java/com/example/domain/Bookmark.java
- src/main/java/com/example/repository/BookmarkRepository.java
- src/main/java/com/example/security/SecurityConfig.java
- src/main/java/com/example/service/BookmarkService.java
- src/main/resources/static/css/item-detail.css
- src/main/resources/static/js/bookmark.js
- src/main/resources/templates/item-detail.html
* ブックマークのアイコン押すと色の切り替わり
* 非同期でテーブルの書き換え
* ログインしていない場合の処理は未実装
> ブックマーク機能の作成

- src/main/java/com/example/controller/ShowItemListController.java
- src/main/resources/static/css/item-list.css
- src/main/resources/static/js/item-list/autoComp.js
- src/main/resources/static/js/pagination.js
- src/main/resources/templates/item-list.html
* cssとjsでページングデザイン
materialize.cssが分からなすぎたので、cssでデザインしています。。。
> ページネーションデザイン

- src/main/resources/templates/my-page.html
- src/main/resources/templates/order-confirm.html
- src/main/resources/templates/register.html
> 番号の入力の際にハイフンの要不要がわかりにくかったのでHTMLで明示的に表示するように修正

- src/main/resources/templates/order-confirm.html
> 注文確定ボタンと購入手続きボタンのテキストが同じになっており分かりにくかったので修正

- src/main/java/com/example/repository/ItemRepository.java
> 大文字小文字を区別せずに検索できるように修正

- src/main/java/com/example/form/UserRegisterForm.java
> パスワードのバリデーションに8文字以上かつ大文字、小文字、数字、および記号を含める必要があるという条件を追加

- src/main/java/com/example/form/OrderForm.java
- src/main/resources/static/css/order-confirm.css
- src/main/resources/static/js/materialize/date-picker.js
- src/main/resources/static/js/order-confirm/control-deliveryTime-option.js
- src/main/resources/templates/order-confirm.html
> 配達時間の選択肢の制御

- src/main/resources/static/css/item-list.css
> ページネーションアイコンのテキストの位置を修正

- src/main/resources/templates/shopping-cart.html
> カート内容表示時にサイズも表示する

- src/main/java/com/example/controller/UserMyPageController.java
- src/main/java/com/example/repository/ItemRepository.java
- src/main/java/com/example/service/UserMyPageService.java
- src/main/resources/static/css/my-page.css
- src/main/resources/static/css/order-history.css
- src/main/resources/templates/my-page.html
> マイページに注文履歴の表示を追加し、デザインも少し修正しました

- src/main/resources/static/js/item-detail/review-chart.js
> ピックアップレビューに適したものがないときに表示しない

- src/main/resources/static/css/shopping-cart.css
> カート内容ページのスタイルを修正
